#!/usr/bin/env bash

# Define colors to be used when echoing output
readonly NC=$(tput sgr0)
readonly BOLD=$(tput bold)
readonly BLACK=$(tput setaf 0)
readonly RED=$(tput setaf 1)
readonly GREEN=$(tput setaf 2)
readonly YELLOW=$(tput setaf 3)
readonly BLUE=$(tput setaf 4)
readonly MAGENTA=$(tput setaf 5)
readonly CYAN=$(tput setaf 6)
readonly WHITE=$(tput setaf 7)

# connect to ethernet via dhcp
echo "${BOLD}${YELLOW}Connecting to network via DHCP..."
dhclient
sleep 1

# sync time with NIST's servers
echo "${BOLD}${YELLOW}Updating system time with time.nist.gov..."
ntpdate -u time.nist.gov
sleep 1

# map file server for log file output
echo "${BOLD}${YELLOW}Mounting file server..."
mkdir -p /mnt/logshare
# mount share using credentials and path provided in tools/fileserver.cfg. Line 1 is share path (ex. //192.168.1.15/path/to/log folder/), line 2 is AD username, line 3 AD password, line 4 AD domain (ex. contoso.local)
# remove Windows newline (^M) from fileserver.cfg. This prevents issues if the cfg was created on a Windows PC.
sed -i -e 's/\r//g' /tmp/tools/fileserver.cfg
mount -o "domain=$(sed '4q;d' /tmp/tools/fileserver.cfg),username=$(sed '2q;d' /tmp/tools/fileserver.cfg),password=$(sed '3q;d' /tmp/tools/fileserver.cfg)" "$(sed '1q;d' /tmp/tools/fileserver.cfg)" /mnt/logshare
sleep 1

# set log location, folder needs to already exist
readonly LOG="/mnt/logshare/$(basename "$0")-$(date '+%Y-%m-%d--%I-%M-%S-%p').log"

# set hddcount to 0 so we can check for them once SSDs have been wiped.
hddcount="0"

# get usb drive path
IFS=$'\n'
for mtabline in `cat /etc/mtab`; do 
  device=`echo $mtabline | cut -f 1 -d ' '`
  udevline=`udevadm info -q path -n $device 2>&1 |grep usb` 
  if [ $? == 0 ] ; then
    devpath=`echo $mtabline | cut -f 2 -d ' '`
    #echo "$devpath"
  fi
done

# kernel name & transfer type, skip dvd drives (sr0)
readonly DISKS=$(lsblk -io KNAME,TRAN,TYPE | awk '/sata|nvme/ && /disk/ && !/sr0/ {print $1}')

usage () {
    echo "
$(basename "$0") [OPTION]

This script must be run with one of the following options.

Options:
  -a, --automate	Automate all disk wiping commands with no need for user input
  -i, --interactive	Query user for each command before running it.
"
}

# make log more readable
logentry () {
    echo >> "$LOG";
    echo "DATE: $(date '+%A %d %B %Y')" >> "$LOG";
    echo "TIME: $(date '+%H:%M:%S')" >> "$LOG";
    echo "OUTPUT FROM TUXNUKEM:" >> "$LOG"
    echo >> "$LOG";
}

# query power adapter presence. use wildcard as different adapters have
# different names...
powercheck () {
    if [[ -d "/proc/acpi/ac_adapter" ]]; then
	until grep -q on-line /proc/acpi/ac_adapter/*/state; do
	    echo -ne "${BOLD}${RED}NO AC ADAPTER DETECTED. CONNECT TO AC TO CONTINUE....${NC}"\\r
	done
	# I'm pretty sure it's not possible to ctrl-c out of the loop (but not the
	# script) without adding a trap, but better safe than sorry!
	if grep -q on-line /proc/acpi/ac_adapter/*/state; then
	    return 0
	else
	    echo "${BOLD}${RED}ABORTING.${NC}"
	    echo
	    exit 1
	fi
    fi
}

# give before and after feedback on state of disk
echopart () {
    local disk="$1"

    echo
    echo "${BOLD}${GREEN}Partition Table of ${YELLOW}/dev/${disk}${MAGENTA}:${NC}"
    echo "${BOLD}${GREEN}"
    echo "DISK DETAILS:" >> "$LOG" 2>&1
    echo >> "$LOG" 2>&1
    lsblk -o NAME,SERIAL,FSTYPE,LABEL,SIZE /dev/"$disk" | tee -a "$LOG"
    echo >> "$LOG" 2>&1
    echo -n "${NC}"
}

# infinite loop to get simple user input
ask () {
    local question="$1"

    while :; do
	# -e for readline bindings
	# -r to not mangle backslashes
	# -n 1 for execution without return
	read -n 1 -rep "$question" ans;
	case $ans in
	    y|Y)
		return 0
		;;
	    n|N)
		return 1
		;;
	    q|Q)
		clear
		exit 0
		;;
	    *)
		echo
		echo "${BOLD}${RED}Enter (y)es, (n)o or (q)uit.${NC}";
		echo
		;;
	esac
    done
}

# sgdisk wrapper to destroy partition table data structures
zap () {
    local disk="$1"

    powercheck

    echo
    echo "${BOLD}${YELLOW}Clearing partition tables...${NC}"

    sgdisk --zap-all /dev/"$disk" >> /dev/null
    partprobe /dev/"$disk" >> /dev/null
    kpartx -u /dev/"$disk" >> /dev/null
	
	echo "Cleared partition tables with: sgdisk --zap-all /dev/$disk" >> "$LOG"
}

zero () {
    local disk="$1"

    powercheck

    echo
    echo "${BOLD}${YELLOW}Zeroing first and last MB...${NC}"

    size=$(blockdev --getsz /dev/"$disk") # size in 512 blocks of disk
    # zero out first MB of disk
    dd if=/dev/zero of=/dev/"$disk" bs=512 count=2048 >> "$LOG" 2>&1
    # zero out last MB of disk
    dd if=/dev/zero of=/dev/"$disk" bs=512 count=2048 seek=$((size - 2048)) >> "$LOG" 2>&1
    partprobe /dev/"$disk" >> "$LOG" 2>&1
    kpartx -u /dev/"$disk" >> "$LOG" 2>&1
    sgdisk --zap-all /dev/"$disk" >> "$LOG" 2>&1
    sgdisk --zap-all /dev/"$disk" >> "$LOG" 2>&1
    partprobe /dev/"$disk" >> "$LOG" 2>&1
    kpartx -u /dev/"$disk" >> "$LOG" 2>&1
}

# use dcfldd as it provides progress feedback unlike dd
random () {
    local disk="$1"

    powercheck

    echo
    echo "${BOLD}${YELLOW}Writing 2GB of random data...${NC}"

    echo "${BOLD}${GREEN}"
    # urandom faster but less cryptographically secure
    dcfldd if=/dev/urandom of=/dev/"$disk" bs=1M count=2048
    sgdisk --zap-all /dev/"$disk" >> "$LOG" 2>&1
    partprobe /dev/"$disk" >> "$LOG" 2>&1
    kpartx -u /dev/"$disk" >> "$LOG" 2>&1
    echo -n "${NC}"
}

nuke () {
    local disk="$1"

    powercheck

    echo
    echo "${BOLD}${MAGENTA}This will take a really long time...${NC}"
    echo
    if ask "${BOLD}${CYAN}Are you sure you want to continue? ${NC}"; then
	echo
	echo "${BOLD}${YELLOW}Nuking disk...${NC}"
	echo "${BOLD}${GREEN}"
	# urandom faster but less cryptographically secure
	dcfldd if=/dev/urandom of=/dev/"$disk" bs=4M
	sgdisk --zap-all /dev/"$disk" >> "$LOG" 2>&1
	partprobe /dev/"$disk" >> "$LOG" 2>&1
	kpartx -u /dev/"$disk" >> "$LOG" 2>&1
	echo -n "${NC}"
    else
	echo
	echo "${BOLD}${MAGENTA}Aborting disk nuke.${NC}"
    fi
}

# check if type of erase is supported.
support () {
    local disk="$1" type="$2"

    if hdparm -I /dev/"$disk"\
	    | grep -Eq "not.*supported.*$type.*erase"; then
	echo
	echo "${BOLD}${MAGENTA}Skipping $type erase. Not supported..${NC}"
	return 1
    else
	echo
	echo "${BOLD}${CYAN}${type^} erase supported.${NC}"
	return 0
    fi
}

# Many BIOSes will protect your disks if you have a password set (security
# enabled) by issuing a SECURITY FREEZE command before booting an operating
# system.
#
# Only suspend or hotplugging the disk unfreezes the state of the disk.
frozen () {
    local disk="$1"

    if [[ "$(hdparm -I /dev/"$disk" | awk '!/not/ && /frozen/')" ]]; then
	echo
	echo "${BOLD}${YELLOW}Disk is frozen. Suspending to unfreeze disk...${NC}"
	sleep 2
	rtcwake -m mem -s 10 >> /dev/null 2>&1 & # automate resume from suspend
	wait $!
	if [[ $? -ne 0 ]]; then
	    echo
	    echo "${BOLD}${RED}Suspend failed.${NC}"
	    return 1
	else
	    echo
	    echo "${BOLD}${YELLOW}Suspend worked. Checking disk status...${NC}"
	    if  frozen "$disk"; then
		return 0;
	    else
		echo
		echo "${BOLD}${RED}Unfreezing failed.${NC}"
		return 1
	    fi
	fi
    else
	echo
	echo "${BOLD}${CYAN}Disk not frozen."
	return 0
    fi
}

nvmerase () {
    local disk="$1"

    nvme format /dev/"$disk" --force >> "$LOG" 2>&1
    if [[ $? -eq 0 ]]; then
	echo
	echo "${BOLD}${CYAN}NVME Erase succeeded on /dev/$disk${NC}"
	echo "NVME Erase succeeded on /dev/$disk" >> "$LOG" 2>&1
    else
	echo
	echo "${BOLD}${RED}NVME Format not supported on /dev/$disk${NC}"
	echo "NVME Format not supported on /dev/$disk" >> "$LOG" 2>&1
    fi

    nvme format --ses=1 /dev/"$disk" --force >> "$LOG" 2>&1
    if [[ $? -eq 0 ]]; then
	echo
	echo "${BOLD}${CYAN}NVME User Data Erase succeeded on /dev/$disk${NC}"
	echo "NVME User Data Erase succeeded on /dev/$disk" >> "$LOG" 2>&1
    else
	echo
	echo "${BOLD}${RED}NVME User Data Erase Not supported on /dev/$disk${NC}"
	echo "NVME User Data Erase Not supported on /dev/$disk" >> "$LOG" 2>&1
    fi

    nvme format --ses=2 /dev/"$disk" --force >> "$LOG" 2>&1
    if [[ $? -eq 0 ]]; then
	echo
	echo "${BOLD}${CYAN}NVME Cryptographic Erase succeeded on /dev/$disk${NC}"
	echo "NVME Cryptographic Erase succeeded on /dev/$disk" >> "$LOG" 2>&1
    else
	echo
	echo "${BOLD}${RED}NVME Cryptographic Erase not supported on /dev/$disk${NC}"
	echo "NVME Cryptographic Erase not supported on /dev/$disk" >> "$LOG" 2>&1
    fi

    return
}

ssderase () {
    local disk="$1" type="$2" erasestr hdparm_pid spin i

    # get time estimate
    if [[ "$type" == "secure" ]]; then
	time=$(hdparm -I /dev/"$disk"\
		   | awk -F. '/SECURITY ERASE/{print $1}'\
		   | sed 's/[^0-9]//g')
	erasestr="erase"
    elif [[ "$type" == "enhanced" ]]; then
	time=$(hdparm -I /dev/"$disk"\
		   | awk -F. '/SECURITY ERASE/{print $2}'\
		   | sed 's/[^0-9]//g')
	erasestr="erase-enhanced"
    fi

    powercheck

    echo
    echo "${BOLD}${YELLOW}Started ${type^} erase. This may take up to $time minutes...${NC}"
    echo
    echo "${BOLD}${RED}DO NOT EXIT OR SHUTDOWN UNTIL THIS FINISHES!${NC}"
	# the security of this password doesn't matter. this is only used to make the ssd clear its cells
	echo "Attempting to clear $disk's cells using hdparm..." >> "$LOG"
    hdparm --user-master u --security-set-pass "password" /dev/"$disk" >> /dev/null 2>&1
    hdparm --user-master u --security-"$erasestr" "password" /dev/"$disk" >> /dev/null 2>&1 &
    hdparm_pid=$!
	echo "Cleared $disk's cells via hdparm password set/removal." >> "$LOG" 2>&1

    # https://stackoverflow.com/questions/12498304/using-bash-to-display-a-progress-working-indicator
    if [[ "$time" -gt 1 ]]; then
	spin='-\|/'
	i=0
	echo "${BOLD}${YELLOW}"
	while kill -0 "$hdparm_pid" 2>/dev/null; do
	    i=$(( (i+1) %4 ))
	    printf "\\r%s ${spin:$i:1} " "Erasing SSD:"
	    sleep .1
	done
	printf "\\r"; printf " %0.s" {0..100} # 100 expansions of the space character to blank last line
    fi

    wait "$hdparm_pid"
    if [[ $? -eq 0 ]]; then
	echo $'\r'"${BOLD}${CYAN}Erase succeeded.${NC}"
    else
	echo $'\r'"${BOLD}${RED}Erase failed.${NC}"
    fi
}

ssdcheck () {
    local disk="$1"

    if [[ "$disk" =~ nvme ]]; then
	echo
	echo "${BOLD}${MAGENTA}NVME device detected.${NC}"
	nvmerase "$disk"
	return
    fi

    if support "$disk" "secure"; then
	if frozen "$disk"; then
	    ssderase "$disk" "secure"
	fi
    fi

    #if support "$disk" "enhanced"; then
	#if frozen "$disk"; then
	#    ssderase "$disk" "enhanced"
	#fi
    #fi
}

hddcheck () {
	local disk="$1"
	local -i ans

	ans=$(cat /sys/block/"$disk"/queue/rotational)

	if ((ans != 0)); then
	echo "${BOLD}${YELLOW}$disk is hdd${NC}"
	let "hddcount = hddcount + 1"
	else
	echo "${BOLD}${YELLOW}$disk is ssd${NC}"
	fi
}

getssd () {
    local disk="$1"
    local -i ans

    ans=$(cat /sys/block/"$disk"/queue/rotational)

    if ((ans == 0)); then
	echo
	echo "${CYAN}${BOLD}SSD detected. Attempting to clear memory cells...${NC}"
	ssdcheck "$disk"
    else
	echo
	echo "${CYAN}${BOLD}No SSD detected. Nothing more to do.${NC}"
    fi
}

finish () {
	echo "${BOLD}${CYAN}Wiping finished. Checking for HDDs to see if we need to run nwipe."
	for disk in $(find /sys/block/*/device/block/*/removable -exec bash -c 'echo {} | perl -ne "\$a=\$_;s/^\/sys\/block\/(.*?)\/.*/\$1/;print if (\`cat \$a\` == "0")"' \;)
	do
		echo "${BOLD}${YELLOW}Checking if $disk is ssd or hdd..."
		hddcheck "$disk"
	done
	#if HDDs are found this will start nwipe to wipe them.
	if ((hddcount == 0)); then
		echo "${CYAN}${BOLD}No HDDs found. Booting into XFCE to run verification...${NC}"
		echo "No HDDs found. This script will now quit out to run verification." >> "$LOG"
		echo "There should be a log file for disk verifier in this folder. Please double check those logs to make sure everything has been wiped successfully." >> "$LOG"
		mkdir -p /home/partedmagic/.config/autostart
		cp "/tmp/tools/autoverify.sh" /tmp/autoverify.sh
		cp "/tmp/tools/autoverify.desktop" /home/partedmagic/.config/autostart/
		chmod +x /tmp/autoverify.sh
		chmod +x /home/partedmagic/.config/autostart/autoverify.desktop
		sleep 5
		exit 0
	else
		echo "${CYAN}${BOLD}HDDs found. Starting nwipe to wipe them...${NC}"
		echo "HDDs found. This script should automatically start nwipe to clear them. There should be a log file for nwipe in this same folder." >> "$LOG"
		mkdir -p /home/partedmagic/.config/autostart
		cp "/tmp/tools/autoverify-nwipe.sh" /tmp/autoverify-nwipe.sh
		cp "/tmp/tools/autoverify-nwipe.desktop" /home/partedmagic/.config/autostart/
		chmod +x /tmp/autoverify-nwipe.sh
		chmod +x /home/partedmagic/.config/autostart/autoverify-nwipe.desktop
		sleep 5
		exit 0
	fi
}

main () {
    local arg="$1"

    echo
    echo -n "${BOLD}${GREEN}Found internal disks${MAGENTA} @ ${NC}"
    for disk in "${DISKS[@]}"; do
	if [[ "$disk" == "${DISKS[-1]}" ]]; then
	    echo "${BOLD}${YELLOW}/dev/$disk${NC}"
	else
	    echo -n "${BOLD}${YELLOW}/dev/$disk${MAGENTA}, "
	fi
    done

    case "$arg" in
	-a|--automate)
	    for disk in "${DISKS[@]}"; do
		powercheck
		echo
		echo "${BOLD}${CYAN}Wiping /dev/$disk${NC}"
		echo "Wiping /dev/$disk" >> "$LOG"
		zap "$disk"
		#zero "$disk"
		#random "$disk"
		getssd "$disk"
		echo "$disk has been wiped." >> "$LOG"
		echo "" >> "$LOG"
	    done
	    finish
	    ;;
	-i|--interactive)
	    for disk in "${DISKS[@]}"; do
		powercheck
		echopart "$disk"
		echo
		if ask "${BOLD}${CYAN}Nuke ${YELLOW}/dev/$disk${CYAN}? ${NC}"; then
		    zap "$disk"
		    zero "$disk"

		    echo
		    if ask "${BOLD}${CYAN}Write 2GB of random data? ${NC}"; then
			random "$disk"
		    else
			echo
			echo "${BOLD}${MAGENTA}Not writing 2GB of random data.${NC}"
		    fi

		    echo
		    if ask "${BOLD}${CYAN}Write random data to whole disk? ${NC}"; then
			nuke "$disk"
		    else
			echo
			echo "${BOLD}${MAGENTA}Not writing random data to whole disk.${NC}"
		    fi
		    getssd "$disk"
		    echopart "$disk"
		else
		    echo
		    echo "${BOLD}${MAGENTA}Not nuking ${YELLOW}/dev/$disk${MAGENTA} from orbit!${NC}"
		fi
	    done
	    finish
	    ;;
	-h|--help)
	    usage
	    ;;
	*)
	    usage
	    ;;
    esac
}

clear
logentry
main "$1"
